-- MySQL Script generated by MySQL Workbench
-- 07/27/17 00:48:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `identificacion` VARCHAR(40) NOT NULL,
  `nombres` VARCHAR(120) NOT NULL,
  `apellidos` VARCHAR(120) NOT NULL,
  `edad` INT(2) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `tipo_identificacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrativo` (
  `persona_identificacion` VARCHAR(40) NOT NULL,
  `clave` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`persona_identificacion`),
  CONSTRAINT `fk_administrativo_persona`
    FOREIGN KEY (`persona_identificacion`)
    REFERENCES `mydb`.`persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rector` (
  `persona_identificacion` VARCHAR(40) NOT NULL,
  `clave` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`persona_identificacion`),
  CONSTRAINT `fk_rector_persona1`
    FOREIGN KEY (`persona_identificacion`)
    REFERENCES `mydb`.`persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `persona_identificacion` VARCHAR(40) NOT NULL,
  `clave` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`persona_identificacion`),
  CONSTRAINT `fk_estudiante_persona1`
    FOREIGN KEY (`persona_identificacion`)
    REFERENCES `mydb`.`persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `persona_identificacion` VARCHAR(40) NOT NULL,
  `clave` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`persona_identificacion`),
  CONSTRAINT `fk_profesor_persona1`
    FOREIGN KEY (`persona_identificacion`)
    REFERENCES `mydb`.`persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `persona_identificacion` VARCHAR(40) NOT NULL,
  `clave` VARCHAR(65) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`persona_identificacion`),
  CONSTRAINT `fk_usuarios_persona1`
    FOREIGN KEY (`persona_identificacion`)
    REFERENCES `mydb`.`persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anio` (
  `id_anio` INT(4) NOT NULL,
  PRIMARY KEY (`id_anio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mes` (
  `id_mes` VARCHAR(25) NOT NULL,
  `anio_id_anio` INT(4) NOT NULL,
  PRIMARY KEY (`id_mes`, `anio_id_anio`),
  INDEX `fk_mes_anio1_idx` (`anio_id_anio` ASC),
  CONSTRAINT `fk_mes_anio1`
    FOREIGN KEY (`anio_id_anio`)
    REFERENCES `mydb`.`anio` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodo` (
  `id_periodo` VARCHAR(65) NOT NULL,
  `anio_id_anio` INT(4) NOT NULL,
  PRIMARY KEY (`id_periodo`, `anio_id_anio`),
  INDEX `fk_periodo_anio1_idx` (`anio_id_anio` ASC),
  CONSTRAINT `fk_periodo_anio1`
    FOREIGN KEY (`anio_id_anio`)
    REFERENCES `mydb`.`anio` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pension` (
  `estudiante_persona_identificacion` VARCHAR(40) NOT NULL,
  `mes_id_mes` VARCHAR(25) NOT NULL,
  `mes_anio_id_anio` INT(4) NOT NULL,
  `pagado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`estudiante_persona_identificacion`, `mes_id_mes`, `mes_anio_id_anio`),
  INDEX `fk_pension_mes1_idx` (`mes_id_mes` ASC, `mes_anio_id_anio` ASC),
  CONSTRAINT `fk_pension_estudiante1`
    FOREIGN KEY (`estudiante_persona_identificacion`)
    REFERENCES `mydb`.`estudiante` (`persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pension_mes1`
    FOREIGN KEY (`mes_id_mes` , `mes_anio_id_anio`)
    REFERENCES `mydb`.`mes` (`id_mes` , `anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matricula` (
  `estudiante_persona_identificacion` VARCHAR(40) NOT NULL,
  `anio_id_anio` INT(4) NOT NULL,
  `pagado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`estudiante_persona_identificacion`, `anio_id_anio`),
  INDEX `fk_matricula_anio1_idx` (`anio_id_anio` ASC),
  CONSTRAINT `fk_matricula_estudiante1`
    FOREIGN KEY (`estudiante_persona_identificacion`)
    REFERENCES `mydb`.`estudiante` (`persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_anio1`
    FOREIGN KEY (`anio_id_anio`)
    REFERENCES `mydb`.`anio` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grado` (
  `nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`primaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`primaria` (
  `grado_nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`grado_nombre`),
  CONSTRAINT `fk_primaria_grado1`
    FOREIGN KEY (`grado_nombre`)
    REFERENCES `mydb`.`grado` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`otros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`otros` (
  `grado_nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`grado_nombre`),
  CONSTRAINT `fk_otros_grado1`
    FOREIGN KEY (`grado_nombre`)
    REFERENCES `mydb`.`grado` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursoprimaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursoprimaria` (
  `id_cursoprimaria` VARCHAR(65) NOT NULL,
  `periodo_id_periodo` VARCHAR(65) NOT NULL,
  `periodo_anio_id_anio` INT(4) NOT NULL,
  `primaria_grado_nombre` VARCHAR(65) NOT NULL,
  `profesor_persona_identificacion` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_cursoprimaria`, `periodo_id_periodo`, `periodo_anio_id_anio`),
  INDEX `fk_cursoprimaria_periodo1_idx` (`periodo_id_periodo` ASC, `periodo_anio_id_anio` ASC),
  INDEX `fk_cursoprimaria_primaria1_idx` (`primaria_grado_nombre` ASC),
  INDEX `fk_cursoprimaria_profesor1_idx` (`profesor_persona_identificacion` ASC),
  CONSTRAINT `fk_cursoprimaria_periodo1`
    FOREIGN KEY (`periodo_id_periodo` , `periodo_anio_id_anio`)
    REFERENCES `mydb`.`periodo` (`id_periodo` , `anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursoprimaria_primaria1`
    FOREIGN KEY (`primaria_grado_nombre`)
    REFERENCES `mydb`.`primaria` (`grado_nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursoprimaria_profesor1`
    FOREIGN KEY (`profesor_persona_identificacion`)
    REFERENCES `mydb`.`profesor` (`persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursootros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursootros` (
  `id_cursootros` VARCHAR(65) NOT NULL,
  `periodo_id_periodo` VARCHAR(65) NOT NULL,
  `periodo_anio_id_anio` INT(4) NOT NULL,
  `otros_grado_nombre` VARCHAR(65) NOT NULL,
  `profesor_persona_identificacion` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_cursootros`, `periodo_id_periodo`, `periodo_anio_id_anio`),
  INDEX `fk_cursootros_periodo1_idx` (`periodo_id_periodo` ASC, `periodo_anio_id_anio` ASC),
  INDEX `fk_cursootros_otros1_idx` (`otros_grado_nombre` ASC),
  INDEX `fk_cursootros_profesor1_idx` (`profesor_persona_identificacion` ASC),
  CONSTRAINT `fk_cursootros_periodo1`
    FOREIGN KEY (`periodo_id_periodo` , `periodo_anio_id_anio`)
    REFERENCES `mydb`.`periodo` (`id_periodo` , `anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursootros_otros1`
    FOREIGN KEY (`otros_grado_nombre`)
    REFERENCES `mydb`.`otros` (`grado_nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursootros_profesor1`
    FOREIGN KEY (`profesor_persona_identificacion`)
    REFERENCES `mydb`.`profesor` (`persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `id_materia` VARCHAR(65) NOT NULL,
  `periodo_id_periodo` VARCHAR(65) NOT NULL,
  `periodo_anio_id_anio` INT(4) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `logro` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_materia`, `periodo_id_periodo`, `periodo_anio_id_anio`),
  INDEX `fk_materia_periodo1_idx` (`periodo_id_periodo` ASC, `periodo_anio_id_anio` ASC),
  CONSTRAINT `fk_materia_periodo1`
    FOREIGN KEY (`periodo_id_periodo` , `periodo_anio_id_anio`)
    REFERENCES `mydb`.`periodo` (`id_periodo` , `anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`codigoprimaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`codigoprimaria` (
  `codigo` VARCHAR(25) NOT NULL,
  `cursoprimaria_id_cursoprimaria` VARCHAR(65) NOT NULL,
  `cursoprimaria_periodo_id_periodo` VARCHAR(65) NOT NULL,
  `cursoprimaria_periodo_anio_id_anio` INT(4) NOT NULL,
  `estudiante_persona_identificacion` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`codigo`, `cursoprimaria_id_cursoprimaria`, `cursoprimaria_periodo_id_periodo`, `cursoprimaria_periodo_anio_id_anio`),
  INDEX `fk_codigoprimaria_cursoprimaria1_idx` (`cursoprimaria_id_cursoprimaria` ASC, `cursoprimaria_periodo_id_periodo` ASC, `cursoprimaria_periodo_anio_id_anio` ASC),
  INDEX `fk_codigoprimaria_estudiante1_idx` (`estudiante_persona_identificacion` ASC),
  CONSTRAINT `fk_codigoprimaria_cursoprimaria1`
    FOREIGN KEY (`cursoprimaria_id_cursoprimaria` , `cursoprimaria_periodo_id_periodo` , `cursoprimaria_periodo_anio_id_anio`)
    REFERENCES `mydb`.`cursoprimaria` (`id_cursoprimaria` , `periodo_id_periodo` , `periodo_anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigoprimaria_estudiante1`
    FOREIGN KEY (`estudiante_persona_identificacion`)
    REFERENCES `mydb`.`estudiante` (`persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`codigootros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`codigootros` (
  `codigo` VARCHAR(25) NOT NULL,
  `cursootros_id_cursootros` VARCHAR(65) NOT NULL,
  `cursootros_periodo_id_periodo` VARCHAR(65) NOT NULL,
  `cursootros_periodo_anio_id_anio` INT(4) NOT NULL,
  `estudiante_persona_identificacion` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`codigo`, `cursootros_id_cursootros`, `cursootros_periodo_id_periodo`, `cursootros_periodo_anio_id_anio`),
  INDEX `fk_codigootros_cursootros1_idx` (`cursootros_id_cursootros` ASC, `cursootros_periodo_id_periodo` ASC, `cursootros_periodo_anio_id_anio` ASC),
  INDEX `fk_codigootros_estudiante1_idx` (`estudiante_persona_identificacion` ASC),
  CONSTRAINT `fk_codigootros_cursootros1`
    FOREIGN KEY (`cursootros_id_cursootros` , `cursootros_periodo_id_periodo` , `cursootros_periodo_anio_id_anio`)
    REFERENCES `mydb`.`cursootros` (`id_cursootros` , `periodo_id_periodo` , `periodo_anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigootros_estudiante1`
    FOREIGN KEY (`estudiante_persona_identificacion`)
    REFERENCES `mydb`.`estudiante` (`persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notaprimaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notaprimaria` (
  `codigoprimaria_codigo` VARCHAR(25) NOT NULL,
  `codigoprimaria_cursoprimaria_id_cursoprimaria` VARCHAR(65) NOT NULL,
  `codigoprimaria_cursoprimaria_periodo_id_periodo` VARCHAR(65) NOT NULL,
  `codigoprimaria_cursoprimaria_periodo_anio_id_anio` INT(4) NOT NULL,
  `materia_id_materia` VARCHAR(65) NOT NULL,
  `materia_periodo_id_periodo` VARCHAR(65) NOT NULL,
  `materia_periodo_anio_id_anio` INT(4) NOT NULL,
  `profesor_persona_identificacion` VARCHAR(40) NOT NULL,
  `nota` DOUBLE NULL,
  `porcentaje` INT(3) NOT NULL,
  `texto` VARCHAR(400) NULL,
  PRIMARY KEY (`codigoprimaria_codigo`, `codigoprimaria_cursoprimaria_id_cursoprimaria`, `codigoprimaria_cursoprimaria_periodo_id_periodo`, `codigoprimaria_cursoprimaria_periodo_anio_id_anio`, `materia_id_materia`, `materia_periodo_id_periodo`, `materia_periodo_anio_id_anio`),
  INDEX `fk_notaprimaria_materia1_idx` (`materia_id_materia` ASC, `materia_periodo_id_periodo` ASC, `materia_periodo_anio_id_anio` ASC),
  INDEX `fk_notaprimaria_profesor1_idx` (`profesor_persona_identificacion` ASC),
  CONSTRAINT `fk_notaprimaria_codigoprimaria1`
    FOREIGN KEY (`codigoprimaria_codigo` , `codigoprimaria_cursoprimaria_id_cursoprimaria` , `codigoprimaria_cursoprimaria_periodo_id_periodo` , `codigoprimaria_cursoprimaria_periodo_anio_id_anio`)
    REFERENCES `mydb`.`codigoprimaria` (`codigo` , `cursoprimaria_id_cursoprimaria` , `cursoprimaria_periodo_id_periodo` , `cursoprimaria_periodo_anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notaprimaria_materia1`
    FOREIGN KEY (`materia_id_materia` , `materia_periodo_id_periodo` , `materia_periodo_anio_id_anio`)
    REFERENCES `mydb`.`materia` (`id_materia` , `periodo_id_periodo` , `periodo_anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notaprimaria_profesor1`
    FOREIGN KEY (`profesor_persona_identificacion`)
    REFERENCES `mydb`.`profesor` (`persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notaotros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notaotros` (
  `codigootros_codigo` VARCHAR(25) NOT NULL,
  `codigootros_cursootros_id_cursootros` VARCHAR(65) NOT NULL,
  `codigootros_cursootros_periodo_id_periodo` VARCHAR(65) NOT NULL,
  `codigootros_cursootros_periodo_anio_id_anio` INT(4) NOT NULL,
  `materia_id_materia` VARCHAR(65) NOT NULL,
  `materia_periodo_id_periodo` VARCHAR(65) NOT NULL,
  `materia_periodo_anio_id_anio` INT(4) NOT NULL,
  `profesor_persona_identificacion` VARCHAR(40) NOT NULL,
  `componente_uno` VARCHAR(120) NULL,
  `componente_dos` VARCHAR(120) NULL,
  `componente_tres` VARCHAR(120) NULL,
  PRIMARY KEY (`codigootros_codigo`, `codigootros_cursootros_id_cursootros`, `codigootros_cursootros_periodo_id_periodo`, `codigootros_cursootros_periodo_anio_id_anio`, `materia_id_materia`, `materia_periodo_id_periodo`, `materia_periodo_anio_id_anio`),
  INDEX `fk_notaotros_materia1_idx` (`materia_id_materia` ASC, `materia_periodo_id_periodo` ASC, `materia_periodo_anio_id_anio` ASC),
  INDEX `fk_notaotros_profesor1_idx` (`profesor_persona_identificacion` ASC),
  CONSTRAINT `fk_notaotros_codigootros1`
    FOREIGN KEY (`codigootros_codigo` , `codigootros_cursootros_id_cursootros` , `codigootros_cursootros_periodo_id_periodo` , `codigootros_cursootros_periodo_anio_id_anio`)
    REFERENCES `mydb`.`codigootros` (`codigo` , `cursootros_id_cursootros` , `cursootros_periodo_id_periodo` , `cursootros_periodo_anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notaotros_materia1`
    FOREIGN KEY (`materia_id_materia` , `materia_periodo_id_periodo` , `materia_periodo_anio_id_anio`)
    REFERENCES `mydb`.`materia` (`id_materia` , `periodo_id_periodo` , `periodo_anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notaotros_profesor1`
    FOREIGN KEY (`profesor_persona_identificacion`)
    REFERENCES `mydb`.`profesor` (`persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notasprimaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notasprimaria` (
  `id_notasprimaria` INT NOT NULL AUTO_INCREMENT,
  `codigoprimaria_codigo` VARCHAR(25) NOT NULL,
  `codigoprimaria_cursoprimaria_id_cursoprimaria` VARCHAR(65) NOT NULL,
  `codigoprimaria_cursoprimaria_periodo_id_periodo` VARCHAR(65) NOT NULL,
  `codigoprimaria_cursoprimaria_periodo_anio_id_anio` INT(4) NOT NULL,
  `materia_id_materia` VARCHAR(65) NOT NULL,
  `materia_periodo_id_periodo` VARCHAR(65) NOT NULL,
  `materia_periodo_anio_id_anio` INT(4) NOT NULL,
  `nota` DOUBLE NULL,
  `porcentaje` INT(3) NOT NULL,
  PRIMARY KEY (`id_notasprimaria`, `codigoprimaria_codigo`, `codigoprimaria_cursoprimaria_id_cursoprimaria`, `codigoprimaria_cursoprimaria_periodo_id_periodo`, `codigoprimaria_cursoprimaria_periodo_anio_id_anio`, `materia_id_materia`, `materia_periodo_id_periodo`, `materia_periodo_anio_id_anio`),
  INDEX `fk_notasprimaria_codigoprimaria1_idx` (`codigoprimaria_codigo` ASC, `codigoprimaria_cursoprimaria_id_cursoprimaria` ASC, `codigoprimaria_cursoprimaria_periodo_id_periodo` ASC, `codigoprimaria_cursoprimaria_periodo_anio_id_anio` ASC),
  INDEX `fk_notasprimaria_materia1_idx` (`materia_id_materia` ASC, `materia_periodo_id_periodo` ASC, `materia_periodo_anio_id_anio` ASC),
  CONSTRAINT `fk_notasprimaria_codigoprimaria1`
    FOREIGN KEY (`codigoprimaria_codigo` , `codigoprimaria_cursoprimaria_id_cursoprimaria` , `codigoprimaria_cursoprimaria_periodo_id_periodo` , `codigoprimaria_cursoprimaria_periodo_anio_id_anio`)
    REFERENCES `mydb`.`codigoprimaria` (`codigo` , `cursoprimaria_id_cursoprimaria` , `cursoprimaria_periodo_id_periodo` , `cursoprimaria_periodo_anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notasprimaria_materia1`
    FOREIGN KEY (`materia_id_materia` , `materia_periodo_id_periodo` , `materia_periodo_anio_id_anio`)
    REFERENCES `mydb`.`materia` (`id_materia` , `periodo_id_periodo` , `periodo_anio_id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
